<?php

class CourseACFIntegration extends \ACFBridge\IntegrationMethods
{
    /**
     * variable for the version
     *
     * @var string
     */
    private static $version = "1.0.0";


    /**
     * Return the instance of the integration
     *
     * @return \ACFBridge\IntegrationMethods
     */
    protected function instance()
    {
        return parent::instance(); // TODO: Change the autogenerated stub
    }


    /**
     * Get the version of the Library
     *
     * @return string
     */
    public static function getVersion()
    {
        return self::$version;
    }

}
