<?php

namespace ACFBridge\Fields\jQuery;

use ACFBridge\Base\ACFInterface\FieldHTML;

class ACF_DatePicker extends FieldHTML
{
    /**
     * @override $fields
     * @var object |array
     */
    protected $field;

    /**
     * @override $fieldType;
     * @var string
     */
    protected $fieldType = "date_picker";

    /**
     * @override acf_default
     * @var array
     */
    protected $acf_default = [
        "field_title" => "",
        "excerpt" => "",
        "type" => "text",
        "required" => 0,
        "width" => "",
        "class" => "",
        "id" => "",
        "default_value" => "",
        "placeholder" => "",
        "maxLength" => "",
        "first_day"
    ];

    /**
     * ACF_Text constructor.
     *
     * @param array $options
     * @param $field
     */
    public function __construct($field, $options = [])
    {
        parent::__construct($field, $options);
        $this->addClass('hasDatepicker');
    }


    /**
     * Custom script based on ACF field data
     */
    public function addScript()
    {
        parent::addScript(); // TODO: Change the autogenerated stub

//        return $script = "<script>
//                let html_id = {$this->html_id}
//
//
//
//            </script>";

    }


}
